### ISSUE TITLE
scanContinue, scanStart and scanCoord panics on invalid input.

### ISSUE THREAD

**Issue by aabizri** [mb0/wkt#2]
While writing [navitia-types](https://github.com/aabizri/navitia-types) I discovered that given abnormal inputs, one of these three functions (and possibly more, I haven't thoroughly checked) panics, unwinding into a panic of `wkt.Parse`.

### Example inputs

- `MULTIPOLYGON(((-11.33535 51.29165,0,0,-11.33535 51.29165))`
- `MULTIPOLYGON((`
- `MULTIPOLYGON(((-11.33535 51.29165,0,0,-11.33535 51.29165)`
- `MULTIPOLYGON(`
- `POLYGON(`
- `MULTIPOLYGON(((0`

### Stack traces

[See this zip](https://github.com/mb0/wkt/files/939142/crashers.zip)

(the .output are the stack traces associated with the input of the corresponding file, I've fitered out the parts related to navitia-types)

**Comment by mb0** [comment]
Thanks for submitting the issue. This packages is a small toy i wrote for a one time import task. I had some fun with embedding in the api design and made it public. I hope it is otherwise useful.

Did you use a fuzzer? If you find more send them over. Have fun!

**Comment by aabizri** [comment]
It is quite useful, and I thank you for providing this package !

Regarding the issue, it seems fixed given a short run with both known invalid inputs and a fuzzer.
I'll let the fuzzer run for 24 hours and get back back at you if I get any more crashers, but I don't think I will.

Closing the issue as it seems fixed by a30afd5.
Thanks again !
